# Generated by Django 3.2.16 on 2024-05-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
