# Generated by Django 3.2.16 on 2024-05-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0003_subscription_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
